branch-defaults:
  default:
    environment: planium-staging
    group_suffix: null
  main:
    environment: planium-staging
environment-defaults:
  planium-staging:
    branch: null
    repository: null
global:
  application_name: planium-backend
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 18
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
